version: "3.9" 

networks:
    logs:

services:
    web:
        image: kamilkhairullin/devops_inno:latest
        container_name: myapp
        networks:
            - logs
        ports:
            - "5000:5000"
        mem_limit: "256m"
        logging:
            driver: "json-file"
            options:
              tag: "{{ .ImageName }}|{{ .Name }}"

    loki:
        image: grafana/loki:${LOKI_VERSION}
        container_name: monitoring-loki
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - logs
        ports:
            - "3100:3100"
        mem_limit: "256m"
        logging:
            options:
                tag: "{{.ImageName}}|{{.Name}}"

    promtail:
        image: grafana/promtail:${PROMTAIL_VERSION}
        command: -config.file=/etc/promtail/config.yml
        container_name: monitoring-promtail
        networks:
            - logs
        volumes:
            - /var/log:/var/log
            - /var/lib/docker/containers/:/var/lib/docker/containers
            - ./promtail.yml:/etc/promtail/config.yml
        mem_limit: "256m"
        logging:
            options:
                tag: "{{.ImageName}}|{{.Name}}"

    grafana:
        image: grafana/grafana:${GRAFNA_VERSION}
        container_name: monitoring-grafana
        networks:
            - logs
        ports:
            - "3000:3000"
        mem_limit: "256m"
        logging:
            options:
                tag: "{{.ImageName}}|{{.Name}}"

    prometheus:
        image: prom/prometheus:${PROMETHEUS_VERSION}
        container_name: prometheus
        ports:
        - 9090:9090
        command: --config.file=/etc/prometheus/prometheus.yml
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - logs
        logging:
            driver: "json-file"
            options:
                tag: "{{.ImageName}}|{{.Name}}"
        mem_limit: "256m"