
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "my-app.fullname" . }}-init-containers"
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "my-app.fullname" . }}:5001']
  restartPolicy: Never