apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: my-app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: Opaque
data:
  username: {{ .Values.secret.username | b64enc | quote }}